package domain;
// Generated 22-dic-2016 13:37:19 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AltaBaja generated by hbm2java
 */
public class AltaBaja  implements java.io.Serializable {


     private int id;
     private Gaixoa gaixoa;
     private Langilea langilea;
     private String entrepresa;
     private String helbidea;
     private String herria;
     private String probintzia;
     private String azterketa;
     private Date eguna;
     private Date hurrengo;
     private Integer iraun;
     private Date baja;

    public AltaBaja() {
    }

	
    public AltaBaja(int id, Gaixoa gaixoa, Langilea langilea) {
        this.id = id;
        this.gaixoa = gaixoa;
        this.langilea = langilea;
    }
    public AltaBaja(int id, Gaixoa gaixoa, Langilea langilea, String entrepresa, String helbidea, String herria, String probintzia, String azterketa, Date eguna, Date hurrengo, Integer iraun, Date baja) {
       this.id = id;
       this.gaixoa = gaixoa;
       this.langilea = langilea;
       this.entrepresa = entrepresa;
       this.helbidea = helbidea;
       this.herria = herria;
       this.probintzia = probintzia;
       this.azterketa = azterketa;
       this.eguna = eguna;
       this.hurrengo = hurrengo;
       this.iraun = iraun;
       this.baja = baja;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Gaixoa getGaixoa() {
        return this.gaixoa;
    }
    
    public void setGaixoa(Gaixoa gaixoa) {
        this.gaixoa = gaixoa;
    }
    public Langilea getLangilea() {
        return this.langilea;
    }
    
    public void setLangilea(Langilea langilea) {
        this.langilea = langilea;
    }
    public String getEntrepresa() {
        return this.entrepresa;
    }
    
    public void setEntrepresa(String entrepresa) {
        this.entrepresa = entrepresa;
    }
    public String getHelbidea() {
        return this.helbidea;
    }
    
    public void setHelbidea(String helbidea) {
        this.helbidea = helbidea;
    }
    public String getHerria() {
        return this.herria;
    }
    
    public void setHerria(String herria) {
        this.herria = herria;
    }
    public String getProbintzia() {
        return this.probintzia;
    }
    
    public void setProbintzia(String probintzia) {
        this.probintzia = probintzia;
    }
    public String getAzterketa() {
        return this.azterketa;
    }
    
    public void setAzterketa(String azterketa) {
        this.azterketa = azterketa;
    }
    public Date getEguna() {
        return this.eguna;
    }
    
    public void setEguna(Date eguna) {
        this.eguna = eguna;
    }
    public Date getHurrengo() {
        return this.hurrengo;
    }
    
    public void setHurrengo(Date hurrengo) {
        this.hurrengo = hurrengo;
    }
    public Integer getIraun() {
        return this.iraun;
    }
    
    public void setIraun(Integer iraun) {
        this.iraun = iraun;
    }
    public Date getBaja() {
        return this.baja;
    }
    
    public void setBaja(Date baja) {
        this.baja = baja;
    }




}


