package domain;
// Generated 22-dic-2016 13:37:19 by Hibernate Tools 4.3.1



/**
 * Bolantea generated by hbm2java
 */
public class Bolantea  implements java.io.Serializable {


     private int id;
     private Gaixoa gaixoa;
     private Langilea langilea;

    public Bolantea() {
    }

    public Bolantea(int id, Gaixoa gaixoa, Langilea langilea) {
       this.id = id;
       this.gaixoa = gaixoa;
       this.langilea = langilea;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Gaixoa getGaixoa() {
        return this.gaixoa;
    }
    
    public void setGaixoa(Gaixoa gaixoa) {
        this.gaixoa = gaixoa;
    }
    public Langilea getLangilea() {
        return this.langilea;
    }
    
    public void setLangilea(Langilea langilea) {
        this.langilea = langilea;
    }




}


