package domain;
// Generated 22-dic-2016 13:37:19 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Errezetak generated by hbm2java
 */
public class Errezetak  implements java.io.Serializable {


     private int id;
     private Gaixoa gaixoa;
     private Langilea langilea;
     private String preskripzioa;
     private String diagnostikoa;
     private String aginduak;
     private Integer iraupena;
     private String posologia;
     private String gomendioak;
     private Date data;
     private String sinadura;

    public Errezetak() {
    }

	
    public Errezetak(int id, Gaixoa gaixoa, Langilea langilea) {
        this.id = id;
        this.gaixoa = gaixoa;
        this.langilea = langilea;
    }
    public Errezetak(int id, Gaixoa gaixoa, Langilea langilea, String preskripzioa, String diagnostikoa, String aginduak, Integer iraupena, String posologia, String gomendioak, Date data, String sinadura) {
       this.id = id;
       this.gaixoa = gaixoa;
       this.langilea = langilea;
       this.preskripzioa = preskripzioa;
       this.diagnostikoa = diagnostikoa;
       this.aginduak = aginduak;
       this.iraupena = iraupena;
       this.posologia = posologia;
       this.gomendioak = gomendioak;
       this.data = data;
       this.sinadura = sinadura;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Gaixoa getGaixoa() {
        return this.gaixoa;
    }
    
    public void setGaixoa(Gaixoa gaixoa) {
        this.gaixoa = gaixoa;
    }
    public Langilea getLangilea() {
        return this.langilea;
    }
    
    public void setLangilea(Langilea langilea) {
        this.langilea = langilea;
    }
    public String getPreskripzioa() {
        return this.preskripzioa;
    }
    
    public void setPreskripzioa(String preskripzioa) {
        this.preskripzioa = preskripzioa;
    }
    public String getDiagnostikoa() {
        return this.diagnostikoa;
    }
    
    public void setDiagnostikoa(String diagnostikoa) {
        this.diagnostikoa = diagnostikoa;
    }
    public String getAginduak() {
        return this.aginduak;
    }
    
    public void setAginduak(String aginduak) {
        this.aginduak = aginduak;
    }
    public Integer getIraupena() {
        return this.iraupena;
    }
    
    public void setIraupena(Integer iraupena) {
        this.iraupena = iraupena;
    }
    public String getPosologia() {
        return this.posologia;
    }
    
    public void setPosologia(String posologia) {
        this.posologia = posologia;
    }
    public String getGomendioak() {
        return this.gomendioak;
    }
    
    public void setGomendioak(String gomendioak) {
        this.gomendioak = gomendioak;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getSinadura() {
        return this.sinadura;
    }
    
    public void setSinadura(String sinadura) {
        this.sinadura = sinadura;
    }




}


