package domain;
// Generated 22-dic-2016 13:37:19 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Froga generated by hbm2java
 */
public class Froga  implements java.io.Serializable {


     private int id;
     private Gaixoa gaixoa;
     private Zentrua zentrua;
     private Integer eskaeraZbk;
     private Date eguna;
     private String izena;
     private String tokia;
     private String eginBehar;

    public Froga() {
    }

	
    public Froga(int id, Gaixoa gaixoa, Zentrua zentrua) {
        this.id = id;
        this.gaixoa = gaixoa;
        this.zentrua = zentrua;
    }
    public Froga(int id, Gaixoa gaixoa, Zentrua zentrua, Integer eskaeraZbk, Date eguna, String izena, String tokia, String eginBehar) {
       this.id = id;
       this.gaixoa = gaixoa;
       this.zentrua = zentrua;
       this.eskaeraZbk = eskaeraZbk;
       this.eguna = eguna;
       this.izena = izena;
       this.tokia = tokia;
       this.eginBehar = eginBehar;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Gaixoa getGaixoa() {
        return this.gaixoa;
    }
    
    public void setGaixoa(Gaixoa gaixoa) {
        this.gaixoa = gaixoa;
    }
    public Zentrua getZentrua() {
        return this.zentrua;
    }
    
    public void setZentrua(Zentrua zentrua) {
        this.zentrua = zentrua;
    }
    public Integer getEskaeraZbk() {
        return this.eskaeraZbk;
    }
    
    public void setEskaeraZbk(Integer eskaeraZbk) {
        this.eskaeraZbk = eskaeraZbk;
    }
    public Date getEguna() {
        return this.eguna;
    }
    
    public void setEguna(Date eguna) {
        this.eguna = eguna;
    }
    public String getIzena() {
        return this.izena;
    }
    
    public void setIzena(String izena) {
        this.izena = izena;
    }
    public String getTokia() {
        return this.tokia;
    }
    
    public void setTokia(String tokia) {
        this.tokia = tokia;
    }
    public String getEginBehar() {
        return this.eginBehar;
    }
    
    public void setEginBehar(String eginBehar) {
        this.eginBehar = eginBehar;
    }




}


