package domain;
// Generated 22-dic-2016 13:37:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gaixoa generated by hbm2java
 */
public class Gaixoa  implements java.io.Serializable {


     private int gz;
     private String izena;
     private String abizena;
     private Integer telefonoa;
     private String helbidea;
     private String pentsioduna;
     private Set<Historiala> historialak = new HashSet<Historiala>(0);
     private Set<AltaBaja> altaBajak = new HashSet<AltaBaja>(0);
     private Set<Larrialdia> larrialdiak = new HashSet<Larrialdia>(0);
     private Set<Bolantea> bolanteak = new HashSet<Bolantea>(0);
     private Set<Tentsioa> tentsioak = new HashSet<Tentsioa>(0);
     private Set<Errezeta> errezetak = new HashSet<Errezeta>(0);
     private Set<Kontsulta> kontsultak = new HashSet<Kontsulta>(0);
     private Set<EspezialitateTxostena> espezialitateTxostenak = new HashSet<EspezialitateTxostena>(0);
     private Set<Froga> frogak = new HashSet<Froga>(0);

    public Gaixoa() {
    }

	
    public Gaixoa(int gz) {
        this.gz = gz;
    }
    public Gaixoa(int gz, String izena, String abizena, Integer telefonoa, String helbidea, String pentsioduna, Set<Historiala> historialas, Set<AltaBaja> altabajas, Set<Larrialdia> larrialdias, Set<Bolantea> bolanteas, Set<Tentsioa> tentsioas, Set<Errezeta> errezetas, Set<Kontsulta> kontsultas, Set<EspezialitateTxostena> espezialitatetxostenas, Set<Froga> frogas) {
       this.gz = gz;
       this.izena = izena;
       this.abizena = abizena;
       this.telefonoa = telefonoa;
       this.helbidea = helbidea;
       this.pentsioduna = pentsioduna;
       this.historialak = historialas;
       this.altaBajak = altabajas;
       this.larrialdiak = larrialdias;
       this.bolanteak = bolanteas;
       this.tentsioak = tentsioas;
       this.errezetak = errezetas;
       this.kontsultak = kontsultas;
       this.espezialitateTxostenak = espezialitatetxostenas;
       this.frogak = frogas;
    }
   
    public int getGz() {
        return this.gz;
    }
    
    public void setGz(int gz) {
        this.gz = gz;
    }
    public String getIzena() {
        return this.izena;
    }
    
    public void setIzena(String izena) {
        this.izena = izena;
    }
    public String getAbizena() {
        return this.abizena;
    }
    
    public void setAbizena(String abizena) {
        this.abizena = abizena;
    }
    public Integer getTelefonoa() {
        return this.telefonoa;
    }
    
    public void setTelefonoa(Integer telefonoa) {
        this.telefonoa = telefonoa;
    }
    public String getHelbidea() {
        return this.helbidea;
    }
    
    public void setHelbidea(String helbidea) {
        this.helbidea = helbidea;
    }
    public String getPentsioduna() {
        return this.pentsioduna;
    }
    
    public void setPentsioduna(String pentsioduna) {
        this.pentsioduna = pentsioduna;
    }
    public Set<Historiala> getHistorialak() {
        return this.historialak;
    }
    
    public void setHistorialak(Set<Historiala> historialak) {
        this.historialak = historialak;
    }
    public Set<AltaBaja> getAltaBajak() {
        return this.altaBajak;
    }
    
    public void setAltaBajak(Set<AltaBaja> altaBajak) {
        this.altaBajak = altaBajak;
    }

    public Set<Larrialdia> getLarrialdiak() {
        return this.larrialdiak;
    }
    
    public void setLarrialdiak(Set<Larrialdia> larrialdiak) {
        this.larrialdiak = larrialdiak;
    }
    public Set<Bolantea> getBolanteak() {
        return this.bolanteak;
    }
    
    public void setBolanteak(Set<Bolantea> bolanteak) {
        this.bolanteak = bolanteak;
    }
    public Set<Tentsioa> getTentsioak() {
        return this.tentsioak;
    }
    
    public void setTentsioak(Set<Tentsioa> tentsioak) {
        this.tentsioak = tentsioak;
    }
    public Set<Errezeta> getErrezetak() {
        return this.errezetak;
    }
    
    public void setErrezetak(Set<Errezeta> errezetak) {
        this.errezetak = errezetak;
    }
    public Set<Kontsulta> getKontsultak() {
        return this.kontsultak;
    }
    
    public void setKontsultak(Set<Kontsulta> kontsultak) {
        this.kontsultak = kontsultak;
    }
    public Set<EspezialitateTxostena> getEspezialitateTxostenak() {
        return this.espezialitateTxostenak;
    }
    
    public void setEspezialitateTxostenak(Set<EspezialitateTxostena> espezialitateTxostenak) {
        this.espezialitateTxostenak = espezialitateTxostenak;
    }
    public Set<Froga> getFrogak() {
        return this.frogak;
    }
    
    public void setFrogak(Set<Froga> frogak) {
        this.frogak = frogak;
    }




}


