package domain;
// Generated 22-dic-2016 13:37:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gaixoa generated by hbm2java
 */
public class Gaixoa  implements java.io.Serializable {


     private int gz;
     private String izena;
     private String abizena;
     private Integer telefonoa;
     private String helbidea;
     private String pentsioduna;
     private Set<Historiala> historialas = new HashSet<Historiala>(0);
     private Set<Altabaja> altabajas = new HashSet<Altabaja>(0);
     private Set<Errezetak> errezetaks = new HashSet<Errezetak>(0);
     private Set<Larrialdia> larrialdias = new HashSet<Larrialdia>(0);
     private Set<Bolantea> bolanteas = new HashSet<Bolantea>(0);
     private Set<Tentsioa> tentsioas = new HashSet<Tentsioa>(0);
     private Set<Errezeta> errezetas = new HashSet<Errezeta>(0);
     private Set<Kontsulta> kontsultas = new HashSet<Kontsulta>(0);
     private Set<Espezialitatetxostena> espezialitatetxostenas = new HashSet<Espezialitatetxostena>(0);
     private Set<Froga> frogas = new HashSet<Froga>(0);

    public Gaixoa() {
    }

	
    public Gaixoa(int gz) {
        this.gz = gz;
    }
    public Gaixoa(int gz, String izena, String abizena, Integer telefonoa, String helbidea, String pentsioduna, Set<Historiala> historialas, Set<Altabaja> altabajas, Set<Errezetak> errezetaks, Set<Larrialdia> larrialdias, Set<Bolantea> bolanteas, Set<Tentsioa> tentsioas, Set<Errezeta> errezetas, Set<Kontsulta> kontsultas, Set<Espezialitatetxostena> espezialitatetxostenas, Set<Froga> frogas) {
       this.gz = gz;
       this.izena = izena;
       this.abizena = abizena;
       this.telefonoa = telefonoa;
       this.helbidea = helbidea;
       this.pentsioduna = pentsioduna;
       this.historialas = historialas;
       this.altabajas = altabajas;
       this.errezetaks = errezetaks;
       this.larrialdias = larrialdias;
       this.bolanteas = bolanteas;
       this.tentsioas = tentsioas;
       this.errezetas = errezetas;
       this.kontsultas = kontsultas;
       this.espezialitatetxostenas = espezialitatetxostenas;
       this.frogas = frogas;
    }
   
    public int getGz() {
        return this.gz;
    }
    
    public void setGz(int gz) {
        this.gz = gz;
    }
    public String getIzena() {
        return this.izena;
    }
    
    public void setIzena(String izena) {
        this.izena = izena;
    }
    public String getAbizena() {
        return this.abizena;
    }
    
    public void setAbizena(String abizena) {
        this.abizena = abizena;
    }
    public Integer getTelefonoa() {
        return this.telefonoa;
    }
    
    public void setTelefonoa(Integer telefonoa) {
        this.telefonoa = telefonoa;
    }
    public String getHelbidea() {
        return this.helbidea;
    }
    
    public void setHelbidea(String helbidea) {
        this.helbidea = helbidea;
    }
    public String getPentsioduna() {
        return this.pentsioduna;
    }
    
    public void setPentsioduna(String pentsioduna) {
        this.pentsioduna = pentsioduna;
    }
    public Set<Historiala> getHistorialas() {
        return this.historialas;
    }
    
    public void setHistorialas(Set<Historiala> historialas) {
        this.historialas = historialas;
    }
    public Set<Altabaja> getAltabajas() {
        return this.altabajas;
    }
    
    public void setAltabajas(Set<Altabaja> altabajas) {
        this.altabajas = altabajas;
    }
    public Set<Errezetak> getErrezetaks() {
        return this.errezetaks;
    }
    
    public void setErrezetaks(Set<Errezetak> errezetaks) {
        this.errezetaks = errezetaks;
    }
    public Set<Larrialdia> getLarrialdias() {
        return this.larrialdias;
    }
    
    public void setLarrialdias(Set<Larrialdia> larrialdias) {
        this.larrialdias = larrialdias;
    }
    public Set<Bolantea> getBolanteas() {
        return this.bolanteas;
    }
    
    public void setBolanteas(Set<Bolantea> bolanteas) {
        this.bolanteas = bolanteas;
    }
    public Set<Tentsioa> getTentsioas() {
        return this.tentsioas;
    }
    
    public void setTentsioas(Set<Tentsioa> tentsioas) {
        this.tentsioas = tentsioas;
    }
    public Set<Errezeta> getErrezetas() {
        return this.errezetas;
    }
    
    public void setErrezetas(Set<Errezeta> errezetas) {
        this.errezetas = errezetas;
    }
    public Set<Kontsulta> getKontsultas() {
        return this.kontsultas;
    }
    
    public void setKontsultas(Set<Kontsulta> kontsultas) {
        this.kontsultas = kontsultas;
    }
    public Set<Espezialitatetxostena> getEspezialitatetxostenas() {
        return this.espezialitatetxostenas;
    }
    
    public void setEspezialitatetxostenas(Set<Espezialitatetxostena> espezialitatetxostenas) {
        this.espezialitatetxostenas = espezialitatetxostenas;
    }
    public Set<Froga> getFrogas() {
        return this.frogas;
    }
    
    public void setFrogas(Set<Froga> frogas) {
        this.frogas = frogas;
    }




}


