package domain;
// Generated 22-dic-2016 13:37:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gela generated by hbm2java
 */
public class Gela  implements java.io.Serializable {


     private int zbk;
     private Set<LarrialdiOrdutegia> larrialdiOrdutegiak = new HashSet<LarrialdiOrdutegia>(0);
     private Set<Ordutegia> ordutegiak = new HashSet<Ordutegia>(0);

    public Gela() {
    }

	
    public Gela(int zbk) {
        this.zbk = zbk;
    }
    public Gela(int zbk, Set<LarrialdiOrdutegia> larrialdiordutegias, Set<Ordutegia> ordutegias) {
       this.zbk = zbk;
       this.larrialdiOrdutegiak = larrialdiordutegias;
       this.ordutegiak = ordutegias;
    }
   
    public int getZbk() {
        return this.zbk;
    }
    
    public void setZbk(int zbk) {
        this.zbk = zbk;
    }
    public Set<LarrialdiOrdutegia> getLarrialdiOrdutegiak() {
        return this.larrialdiOrdutegiak;
    }
    
    public void setLarrialdiOrdutegiak(Set<LarrialdiOrdutegia> larrialdiOrdutegiak) {
        this.larrialdiOrdutegiak = larrialdiOrdutegiak;
    }
    public Set<Ordutegia> getOrdutegiak() {
        return this.ordutegiak;
    }
    
    public void setOrdutegiak(Set<Ordutegia> ordutegiak) {
        this.ordutegiak = ordutegiak;
    }




}


