package domain;
// Generated 22-dic-2016 13:37:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gela generated by hbm2java
 */
public class Gela  implements java.io.Serializable {


     private int zbk;
     private Set<Larrialdiordutegia> larrialdiordutegias = new HashSet<Larrialdiordutegia>(0);
     private Set<Ordutegia> ordutegias = new HashSet<Ordutegia>(0);

    public Gela() {
    }

	
    public Gela(int zbk) {
        this.zbk = zbk;
    }
    public Gela(int zbk, Set<Larrialdiordutegia> larrialdiordutegias, Set<Ordutegia> ordutegias) {
       this.zbk = zbk;
       this.larrialdiordutegias = larrialdiordutegias;
       this.ordutegias = ordutegias;
    }
   
    public int getZbk() {
        return this.zbk;
    }
    
    public void setZbk(int zbk) {
        this.zbk = zbk;
    }
    public Set<Larrialdiordutegia> getLarrialdiordutegias() {
        return this.larrialdiordutegias;
    }
    
    public void setLarrialdiordutegias(Set<Larrialdiordutegia> larrialdiordutegias) {
        this.larrialdiordutegias = larrialdiordutegias;
    }
    public Set<Ordutegia> getOrdutegias() {
        return this.ordutegias;
    }
    
    public void setOrdutegias(Set<Ordutegia> ordutegias) {
        this.ordutegias = ordutegias;
    }




}


