package domain;
// Generated 22-dic-2016 13:37:19 by Hibernate Tools 4.3.1



/**
 * Historiala generated by hbm2java
 */
public class Historiala  implements java.io.Serializable {


     private int id;
     private Gaixoa gaixoa;
     private String deskribapena;

    public Historiala() {
    }

	
    public Historiala(int id, Gaixoa gaixoa) {
        this.id = id;
        this.gaixoa = gaixoa;
    }
    public Historiala(int id, Gaixoa gaixoa, String deskribapena) {
       this.id = id;
       this.gaixoa = gaixoa;
       this.deskribapena = deskribapena;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Gaixoa getGaixoa() {
        return this.gaixoa;
    }
    
    public void setGaixoa(Gaixoa gaixoa) {
        this.gaixoa = gaixoa;
    }
    public String getDeskribapena() {
        return this.deskribapena;
    }
    
    public void setDeskribapena(String deskribapena) {
        this.deskribapena = deskribapena;
    }




}


