package domain;
// Generated 22-dic-2016 13:37:19 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Kontsulta generated by hbm2java
 */
public class Kontsulta  implements java.io.Serializable {


     private int id;
     private Gaixoa gaixoa;
     private Langilea langilea;
     private Date eguna;
     private Integer ordua;

    public Kontsulta() {
    }

	
    public Kontsulta(int id, Gaixoa gaixoa, Langilea langilea) {
        this.id = id;
        this.gaixoa = gaixoa;
        this.langilea = langilea;
    }
    public Kontsulta(int id, Gaixoa gaixoa, Langilea langilea, Date eguna, Integer ordua) {
       this.id = id;
       this.gaixoa = gaixoa;
       this.langilea = langilea;
       this.eguna = eguna;
       this.ordua = ordua;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Gaixoa getGaixoa() {
        return this.gaixoa;
    }
    
    public void setGaixoa(Gaixoa gaixoa) {
        this.gaixoa = gaixoa;
    }
    public Langilea getLangilea() {
        return this.langilea;
    }
    
    public void setLangilea(Langilea langilea) {
        this.langilea = langilea;
    }
    public Date getEguna() {
        return this.eguna;
    }
    
    public void setEguna(Date eguna) {
        this.eguna = eguna;
    }
    public Integer getOrdua() {
        return this.ordua;
    }
    
    public void setOrdua(Integer ordua) {
        this.ordua = ordua;
    }




}


