package domain;
// Generated 22-dic-2016 13:37:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Langilea generated by hbm2java
 */
public class Langilea  implements java.io.Serializable {


     private int gz;
     private Zentrua zentrua;
     private String erabiltzailea;
     private String pasahitza;
     private String izena;
     private String abizena;
     private Integer telefonoa;
     private String helbidea;
     private Integer mota;
     private Integer espIzena;
     private Set<Espezialitatetxostena> espezialitatetxostenas = new HashSet<Espezialitatetxostena>(0);
     private Set<Errezeta> errezetas = new HashSet<Errezeta>(0);
     private Set<Altabaja> altabajas = new HashSet<Altabaja>(0);
     private Set<Errezetak> errezetaks = new HashSet<Errezetak>(0);
     private Set<Larrialdia> larrialdias = new HashSet<Larrialdia>(0);
     private Set<Ordutegia> ordutegias = new HashSet<Ordutegia>(0);
     private Set<Kontsulta> kontsultas = new HashSet<Kontsulta>(0);
     private Set<Larrialdiordutegia> larrialdiordutegias = new HashSet<Larrialdiordutegia>(0);
     private Set<Bolantea> bolanteas = new HashSet<Bolantea>(0);

    public Langilea() {
    }

	
    public Langilea(int gz, Zentrua zentrua) {
        this.gz = gz;
        this.zentrua = zentrua;
    }
    public Langilea(int gz, Zentrua zentrua, String erabiltzailea, String pasahitza, String izena, String abizena, Integer telefonoa, String helbidea, Integer mota, Integer espIzena, Set<Espezialitatetxostena> espezialitatetxostenas, Set<Errezeta> errezetas, Set<Altabaja> altabajas, Set<Errezetak> errezetaks, Set<Larrialdia> larrialdias, Set<Ordutegia> ordutegias, Set<Kontsulta> kontsultas, Set<Larrialdiordutegia> larrialdiordutegias, Set<Bolantea> bolanteas) {
       this.gz = gz;
       this.zentrua = zentrua;
       this.erabiltzailea = erabiltzailea;
       this.pasahitza = pasahitza;
       this.izena = izena;
       this.abizena = abizena;
       this.telefonoa = telefonoa;
       this.helbidea = helbidea;
       this.mota = mota;
       this.espIzena = espIzena;
       this.espezialitatetxostenas = espezialitatetxostenas;
       this.errezetas = errezetas;
       this.altabajas = altabajas;
       this.errezetaks = errezetaks;
       this.larrialdias = larrialdias;
       this.ordutegias = ordutegias;
       this.kontsultas = kontsultas;
       this.larrialdiordutegias = larrialdiordutegias;
       this.bolanteas = bolanteas;
    }
   
    public int getGz() {
        return this.gz;
    }
    
    public void setGz(int gz) {
        this.gz = gz;
    }
    public Zentrua getZentrua() {
        return this.zentrua;
    }
    
    public void setZentrua(Zentrua zentrua) {
        this.zentrua = zentrua;
    }
    public String getErabiltzailea() {
        return this.erabiltzailea;
    }
    
    public void setErabiltzailea(String erabiltzailea) {
        this.erabiltzailea = erabiltzailea;
    }
    public String getPasahitza() {
        return this.pasahitza;
    }
    
    public void setPasahitza(String pasahitza) {
        this.pasahitza = pasahitza;
    }
    public String getIzena() {
        return this.izena;
    }
    
    public void setIzena(String izena) {
        this.izena = izena;
    }
    public String getAbizena() {
        return this.abizena;
    }
    
    public void setAbizena(String abizena) {
        this.abizena = abizena;
    }
    public Integer getTelefonoa() {
        return this.telefonoa;
    }
    
    public void setTelefonoa(Integer telefonoa) {
        this.telefonoa = telefonoa;
    }
    public String getHelbidea() {
        return this.helbidea;
    }
    
    public void setHelbidea(String helbidea) {
        this.helbidea = helbidea;
    }
    public Integer getMota() {
        return this.mota;
    }
    
    public void setMota(Integer mota) {
        this.mota = mota;
    }
    public Integer getEspIzena() {
        return this.espIzena;
    }
    
    public void setEspIzena(Integer espIzena) {
        this.espIzena = espIzena;
    }
    public Set<Espezialitatetxostena> getEspezialitatetxostenas() {
        return this.espezialitatetxostenas;
    }
    
    public void setEspezialitatetxostenas(Set<Espezialitatetxostena> espezialitatetxostenas) {
        this.espezialitatetxostenas = espezialitatetxostenas;
    }
    public Set<Errezeta> getErrezetas() {
        return this.errezetas;
    }
    
    public void setErrezetas(Set<Errezeta> errezetas) {
        this.errezetas = errezetas;
    }
    public Set<Altabaja> getAltabajas() {
        return this.altabajas;
    }
    
    public void setAltabajas(Set<Altabaja> altabajas) {
        this.altabajas = altabajas;
    }
    public Set<Errezetak> getErrezetaks() {
        return this.errezetaks;
    }
    
    public void setErrezetaks(Set<Errezetak> errezetaks) {
        this.errezetaks = errezetaks;
    }
    public Set<Larrialdia> getLarrialdias() {
        return this.larrialdias;
    }
    
    public void setLarrialdias(Set<Larrialdia> larrialdias) {
        this.larrialdias = larrialdias;
    }
    public Set<Ordutegia> getOrdutegias() {
        return this.ordutegias;
    }
    
    public void setOrdutegias(Set<Ordutegia> ordutegias) {
        this.ordutegias = ordutegias;
    }
    public Set<Kontsulta> getKontsultas() {
        return this.kontsultas;
    }
    
    public void setKontsultas(Set<Kontsulta> kontsultas) {
        this.kontsultas = kontsultas;
    }
    public Set<Larrialdiordutegia> getLarrialdiordutegias() {
        return this.larrialdiordutegias;
    }
    
    public void setLarrialdiordutegias(Set<Larrialdiordutegia> larrialdiordutegias) {
        this.larrialdiordutegias = larrialdiordutegias;
    }
    public Set<Bolantea> getBolanteas() {
        return this.bolanteas;
    }
    
    public void setBolanteas(Set<Bolantea> bolanteas) {
        this.bolanteas = bolanteas;
    }




}


