package domain;
// Generated 22-dic-2016 13:37:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Langilea generated by hbm2java
 */
public class Langilea  implements java.io.Serializable {


     private int gz;
     private Zentrua zentrua;
     private String erabiltzailea;
     private String pasahitza;
     private String izena;
     private String abizena;
     private Integer telefonoa;
     private String helbidea;
     private String mota;
     private String espIzena;
     private Set<EspezialitateTxostena> espezialitateTxostenak = new HashSet<EspezialitateTxostena>(0);
     private Set<Errezeta> errezetak = new HashSet<Errezeta>(0);
     private Set<AltaBaja> altaBajak = new HashSet<AltaBaja>(0);
     private Set<Larrialdia> larrialdiak = new HashSet<Larrialdia>(0);
     private Set<Ordutegia> ordutegiak = new HashSet<Ordutegia>(0);
     private Set<Kontsulta> kontsultak = new HashSet<Kontsulta>(0);
     private Set<LarrialdiOrdutegia> larrialdiOrdutegiak = new HashSet<LarrialdiOrdutegia>(0);
     private Set<Bolantea> bolanteak = new HashSet<Bolantea>(0);

    public Langilea() {
    }

	
    public Langilea(int gz, Zentrua zentrua) {
        this.gz = gz;
        this.zentrua = zentrua;
    }
    public Langilea(int gz, Zentrua zentrua, String erabiltzailea, String pasahitza, String izena, String abizena, Integer telefonoa, String helbidea, String mota, String espIzena, Set<EspezialitateTxostena> espezialitatetxostenas, Set<Errezeta> errezetas, Set<AltaBaja> altabajas, Set<Larrialdia> larrialdias, Set<Ordutegia> ordutegias, Set<Kontsulta> kontsultas, Set<LarrialdiOrdutegia> larrialdiordutegias, Set<Bolantea> bolanteas) {
       this.gz = gz;
       this.zentrua = zentrua;
       this.erabiltzailea = erabiltzailea;
       this.pasahitza = pasahitza;
       this.izena = izena;
       this.abizena = abizena;
       this.telefonoa = telefonoa;
       this.helbidea = helbidea;
       this.mota = mota;
       this.espIzena = espIzena;
       this.espezialitateTxostenak = espezialitatetxostenas;
       this.errezetak = errezetas;
       this.altaBajak = altabajas;
       this.larrialdiak = larrialdias;
       this.ordutegiak = ordutegias;
       this.kontsultak = kontsultas;
       this.larrialdiOrdutegiak = larrialdiordutegias;
       this.bolanteak = bolanteas;
    }
   
    public int getGz() {
        return this.gz;
    }
    
    public void setGz(int gz) {
        this.gz = gz;
    }
    public Zentrua getZentrua() {
        return this.zentrua;
    }
    
    public void setZentrua(Zentrua zentrua) {
        this.zentrua = zentrua;
    }
    public String getErabiltzailea() {
        return this.erabiltzailea;
    }
    
    public void setErabiltzailea(String erabiltzailea) {
        this.erabiltzailea = erabiltzailea;
    }
    public String getPasahitza() {
        return this.pasahitza;
    }
    
    public void setPasahitza(String pasahitza) {
        this.pasahitza = pasahitza;
    }
    public String getIzena() {
        return this.izena;
    }
    
    public void setIzena(String izena) {
        this.izena = izena;
    }
    public String getAbizena() {
        return this.abizena;
    }
    
    public void setAbizena(String abizena) {
        this.abizena = abizena;
    }
    public Integer getTelefonoa() {
        return this.telefonoa;
    }
    
    public void setTelefonoa(Integer telefonoa) {
        this.telefonoa = telefonoa;
    }
    public String getHelbidea() {
        return this.helbidea;
    }
    
    public void setHelbidea(String helbidea) {
        this.helbidea = helbidea;
    }
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }
    public String getEspIzena() {
        return this.espIzena;
    }
    
    public void setEspIzena(String espIzena) {
        this.espIzena = espIzena;
    }
    public Set<EspezialitateTxostena> getEspezialitateTxostenak() {
        return this.espezialitateTxostenak;
    }
    
    public void setEspezialitateTxostenak(Set<EspezialitateTxostena> espezialitateTxostenak) {
        this.espezialitateTxostenak = espezialitateTxostenak;
    }
    public Set<Errezeta> getErrezetak() {
        return this.errezetak;
    }
    
    public void setErrezetak(Set<Errezeta> errezetak) {
        this.errezetak = errezetak;
    }
    public Set<AltaBaja> getAltaBajak() {
        return this.altaBajak;
    }
    
    public void setAltaBajak(Set<AltaBaja> altaBajak) {
        this.altaBajak = altaBajak;
    }

    public Set<Larrialdia> getLarrialdiak() {
        return this.larrialdiak;
    }
    
    public void setLarrialdiak(Set<Larrialdia> larrialdiak) {
        this.larrialdiak = larrialdiak;
    }
    public Set<Ordutegia> getOrdutegiak() {
        return this.ordutegiak;
    }
    
    public void setOrdutegiak(Set<Ordutegia> ordutegiak) {
        this.ordutegiak = ordutegiak;
    }
    public Set<Kontsulta> getKontsultak() {
        return this.kontsultak;
    }
    
    public void setKontsultak(Set<Kontsulta> kontsultak) {
        this.kontsultak = kontsultak;
    }
    public Set<LarrialdiOrdutegia> getLarrialdiOrdutegiak() {
        return this.larrialdiOrdutegiak;
    }
    
    public void setLarrialdiOrdutegiak(Set<LarrialdiOrdutegia> larrialdiOrdutegiak) {
        this.larrialdiOrdutegiak = larrialdiOrdutegiak;
    }
    public Set<Bolantea> getBolanteak() {
        return this.bolanteak;
    }
    
    public void setBolanteak(Set<Bolantea> bolanteak) {
        this.bolanteak = bolanteak;
    }




}


