package domain;
// Generated 22-dic-2016 13:37:19 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LarrialdiOrdutegia generated by hbm2java
 */
public class LarrialdiOrdutegia  implements java.io.Serializable {


     private int id;
     private Gela gela;
     private Langilea langilea;
     private Date eguna;
     private Integer ordua;

    public LarrialdiOrdutegia() {
    }

	
    public LarrialdiOrdutegia(int id, Gela gela, Langilea langilea) {
        this.id = id;
        this.gela = gela;
        this.langilea = langilea;
    }
    public LarrialdiOrdutegia(int id, Gela gela, Langilea langilea, Date eguna, Integer ordua) {
       this.id = id;
       this.gela = gela;
       this.langilea = langilea;
       this.eguna = eguna;
       this.ordua = ordua;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Gela getGela() {
        return this.gela;
    }
    
    public void setGela(Gela gela) {
        this.gela = gela;
    }
    public Langilea getLangilea() {
        return this.langilea;
    }
    
    public void setLangilea(Langilea langilea) {
        this.langilea = langilea;
    }
    public Date getEguna() {
        return this.eguna;
    }
    
    public void setEguna(Date eguna) {
        this.eguna = eguna;
    }
    public Integer getOrdua() {
        return this.ordua;
    }
    
    public void setOrdua(Integer ordua) {
        this.ordua = ordua;
    }




}


