package domain;
// Generated 22-dic-2016 13:37:19 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tentsioa generated by hbm2java
 */
public class Tentsioa  implements java.io.Serializable {


     private int id;
     private Gaixoa gaixoa;
     private Date eguna;
     private Integer altua;
     private Integer baxua;

    public Tentsioa() {
    }

	
    public Tentsioa(int id, Gaixoa gaixoa) {
        this.id = id;
        this.gaixoa = gaixoa;
    }
    public Tentsioa(int id, Gaixoa gaixoa, Date eguna, Integer altua, Integer baxua) {
       this.id = id;
       this.gaixoa = gaixoa;
       this.eguna = eguna;
       this.altua = altua;
       this.baxua = baxua;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Gaixoa getGaixoa() {
        return this.gaixoa;
    }
    
    public void setGaixoa(Gaixoa gaixoa) {
        this.gaixoa = gaixoa;
    }
    public Date getEguna() {
        return this.eguna;
    }
    
    public void setEguna(Date eguna) {
        this.eguna = eguna;
    }
    public Integer getAltua() {
        return this.altua;
    }
    
    public void setAltua(Integer altua) {
        this.altua = altua;
    }
    public Integer getBaxua() {
        return this.baxua;
    }
    
    public void setBaxua(Integer baxua) {
        this.baxua = baxua;
    }




}


