package domain;
// Generated 22-dic-2016 13:37:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Zentrua generated by hbm2java
 */
public class Zentrua  implements java.io.Serializable {


     private int zid;
     private String izena;
     private String hiria;
     private Integer telefonoa;
     private Set<Froga> frogas = new HashSet<Froga>(0);
     private Set<Langilea> langileas = new HashSet<Langilea>(0);

    public Zentrua() {
    }

	
    public Zentrua(int zid) {
        this.zid = zid;
    }
    public Zentrua(int zid, String izena, String hiria, Integer telefonoa, Set<Froga> frogas, Set<Langilea> langileas) {
       this.zid = zid;
       this.izena = izena;
       this.hiria = hiria;
       this.telefonoa = telefonoa;
       this.frogas = frogas;
       this.langileas = langileas;
    }
   
    public int getZid() {
        return this.zid;
    }
    
    public void setZid(int zid) {
        this.zid = zid;
    }
    public String getIzena() {
        return this.izena;
    }
    
    public void setIzena(String izena) {
        this.izena = izena;
    }
    public String getHiria() {
        return this.hiria;
    }
    
    public void setHiria(String hiria) {
        this.hiria = hiria;
    }
    public Integer getTelefonoa() {
        return this.telefonoa;
    }
    
    public void setTelefonoa(Integer telefonoa) {
        this.telefonoa = telefonoa;
    }
    public Set<Froga> getFrogas() {
        return this.frogas;
    }
    
    public void setFrogas(Set<Froga> frogas) {
        this.frogas = frogas;
    }
    public Set<Langilea> getLangileas() {
        return this.langileas;
    }
    
    public void setLangileas(Set<Langilea> langileas) {
        this.langileas = langileas;
    }




}


